import type { MatchedTradeRecord } from "@/lib/types";
import { sanitizeCSVCell } from "@/lib/utils/export";

// FY2025-26 tax rates (Finance Act 2024)
const LTCG_EXEMPTION = 125000; // Rs 1.25 lakh
const LTCG_TAX_RATE = 0.125; // 12.5%
const STCG_TAX_RATE = 0.20; // 20%
const LONG_TERM_DAYS_EQ = 365; // Equity: >12 months = LTCG
const LONG_TERM_DAYS_FO = 365; // F&O: always STCG (business income), but we classify anyway

export interface TaxClassifiedTrade {
  symbol: string;
  segment: string;
  entryDate: string;
  exitDate: string;
  entryPrice: number;
  exitPrice: number;
  quantity: number;
  holdingDays: number;
  grossPnl: number;
  taxType: "STCG" | "LTCG";
}

export interface TaxSummary {
  trades: TaxClassifiedTrade[];
  stcg: {
    count: number;
    totalPnl: number;
    taxableGain: number;
    estimatedTax: number;
  };
  ltcg: {
    count: number;
    totalPnl: number;
    exemption: number;
    taxableGain: number;
    estimatedTax: number;
  };
  totalEstimatedTax: number;
}

export function computeTaxReport(
  trades: MatchedTradeRecord[],
  financialYear?: string
): TaxSummary {
  let closed = trades.filter((t) => t.status === "CLOSED");

  if (financialYear) {
    closed = closed.filter((t) => t.financialYear === financialYear);
  }

  const classified: TaxClassifiedTrade[] = closed.map((t) => {
    // F&O is always short-term (treated as business income)
    // Equity: >365 days = LTCG
    const isLongTerm =
      t.segment === "EQ" && t.holdingDays > LONG_TERM_DAYS_EQ;

    return {
      symbol: t.symbol,
      segment: t.segment,
      entryDate: t.entryDate.slice(0, 10),
      exitDate: t.exitDate.slice(0, 10),
      entryPrice: t.entryPrice,
      exitPrice: t.exitPrice,
      quantity: t.quantity,
      holdingDays: t.holdingDays,
      grossPnl: t.pnl,
      taxType: isLongTerm ? "LTCG" : "STCG",
    };
  });

  // STCG computation
  const stcgTrades = classified.filter((t) => t.taxType === "STCG");
  const stcgPnl = stcgTrades.reduce((s, t) => s + t.grossPnl, 0);
  const stcgTaxable = Math.max(0, stcgPnl);
  const stcgTax = stcgTaxable * STCG_TAX_RATE;

  // LTCG computation with exemption
  const ltcgTrades = classified.filter((t) => t.taxType === "LTCG");
  const ltcgPnl = ltcgTrades.reduce((s, t) => s + t.grossPnl, 0);
  const ltcgExemption = Math.min(Math.max(0, ltcgPnl), LTCG_EXEMPTION);
  const ltcgTaxable = Math.max(0, ltcgPnl - LTCG_EXEMPTION);
  const ltcgTax = ltcgTaxable * LTCG_TAX_RATE;

  return {
    trades: classified.sort((a, b) => a.exitDate.localeCompare(b.exitDate)),
    stcg: {
      count: stcgTrades.length,
      totalPnl: stcgPnl,
      taxableGain: stcgTaxable,
      estimatedTax: Math.round(stcgTax),
    },
    ltcg: {
      count: ltcgTrades.length,
      totalPnl: ltcgPnl,
      exemption: ltcgExemption,
      taxableGain: ltcgTaxable,
      estimatedTax: Math.round(ltcgTax),
    },
    totalEstimatedTax: Math.round(stcgTax + ltcgTax),
  };
}

export function exportTaxReportCSV(summary: TaxSummary): string {
  const headers = [
    "Symbol",
    "Segment",
    "Tax Type",
    "Entry Date",
    "Exit Date",
    "Entry Price",
    "Exit Price",
    "Quantity",
    "Holding Days",
    "Gross P&L",
  ];

  const rows = summary.trades.map((t) => [
    sanitizeCSVCell(t.symbol),
    t.segment,
    t.taxType,
    t.entryDate,
    t.exitDate,
    t.entryPrice.toFixed(2),
    t.exitPrice.toFixed(2),
    t.quantity,
    t.holdingDays,
    t.grossPnl.toFixed(2),
  ]);

  const csv = [
    headers.join(","),
    ...rows.map((row) => row.map((cell) => `"${cell}"`).join(",")),
    "",
    `"STCG Total P&L","${summary.stcg.totalPnl.toFixed(2)}"`,
    `"STCG Taxable Gain","${summary.stcg.taxableGain.toFixed(2)}"`,
    `"STCG Estimated Tax (20%)","${summary.stcg.estimatedTax.toFixed(2)}"`,
    "",
    `"LTCG Total P&L","${summary.ltcg.totalPnl.toFixed(2)}"`,
    `"LTCG Exemption (Sec 112A)","${summary.ltcg.exemption.toFixed(2)}"`,
    `"LTCG Taxable Gain","${summary.ltcg.taxableGain.toFixed(2)}"`,
    `"LTCG Estimated Tax (12.5%)","${summary.ltcg.estimatedTax.toFixed(2)}"`,
    "",
    `"Total Estimated Tax","${summary.totalEstimatedTax.toFixed(2)}"`,
    "",
    `"Generated by Hisaab (hisaab.trymetis.app) | AI-powered stock analysis at trymetis.app"`,
    `"Disclaimer: This is an estimate. Consult a CA for actual tax filing."`,
  ].join("\n");

  return csv;
}
