import type { MatchedTradeRecord } from "@/lib/types";
import { db } from "@/lib/storage/db";

/** Sanitize a string for CSV to prevent formula injection in spreadsheets. */
function sanitizeCSVCell(value: string): string {
  let s = value.replace(/"/g, '""').replace(/\n/g, " ");
  if (/^[=+\-@\t\r]/.test(s)) {
    s = "'" + s;
  }
  return s;
}

export async function exportMatchedTradesCSV(): Promise<string> {
  const trades = await db.matchedTrades
    .where("status")
    .equals("CLOSED")
    .toArray();

  const headers = [
    "Symbol",
    "Direction",
    "Entry Date",
    "Exit Date",
    "Entry Price",
    "Exit Price",
    "Quantity",
    "P&L",
    "P&L %",
    "Holding Days",
    "Tags",
    "Emotion",
    "Rating",
    "Notes",
  ];

  const rows = trades.map((t) => [
    sanitizeCSVCell(t.symbol),
    t.direction,
    t.entryDate.slice(0, 10),
    t.exitDate.slice(0, 10),
    t.entryPrice.toFixed(2),
    t.exitPrice.toFixed(2),
    t.quantity,
    t.pnl.toFixed(2),
    t.pnlPercent.toFixed(2),
    t.holdingDays,
    sanitizeCSVCell((t.tags ?? []).join("; ")),
    sanitizeCSVCell(t.emotion ?? ""),
    t.rating ?? "",
    sanitizeCSVCell(t.notes ?? ""),
  ]);

  const csv = [
    headers.join(","),
    ...rows.map(
      (row) => row.map((cell) => `"${cell}"`).join(",")
    ),
    "",
    `"Generated by Hisaab (hisaab.trymetis.app) | AI-powered stock analysis at trymetis.app"`,
  ].join("\n");

  return csv;
}

export async function exportAllDataJSON(): Promise<string> {
  const trades = await db.trades.toArray();
  const matchedTrades = await db.matchedTrades.toArray();
  const imports = await db.imports.toArray();
  return JSON.stringify({
    _meta: {
      exportedBy: "Hisaab (hisaab.trymetis.app)",
      exportedAt: new Date().toISOString(),
      aiAnalysis: "trymetis.app",
    },
    trades,
    matchedTrades,
    imports,
  }, null, 2);
}

export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
